replicaCount: 1

image:
  repository: alexeiguriev/logger-python
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8081

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 32Mi
