apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: {{ .Values.api.image }}
        imagePullPolicy: Never
        ports:
        - containerPort: {{ .Values.api.port }}
        env:
        - name: EXECUTOR_URL
          valueFrom:
            configMapKeyRef:
              name: api-configmap
              key: executor_url
