apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - port: {{ .Values.api.port }}
    targetPort: {{ .Values.api.port }}
    nodePort: {{ .Values.api.nodePort }}
