apiVersion: v1
kind: Service
metadata:
  name: executor-service
spec:
  type: NodePort
  selector:
    app: executor
  ports:
  - port: {{ .Values.executor.port }}
    targetPort: {{ .Values.executor.port }}
    nodePort: {{ .Values.executor.nodePort }}