apiVersion: apps/v1
kind: Deployment
metadata:
  name: c-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: c-web
  template:
    metadata:
      labels:
        app: c-web
    spec:
      containers:
        - name: c-web-server
          image: alexeiguriev/c-web-server:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
            requests:
              memory: "32Mi"
              cpu: "50m"
